name: Elastic docs

on:
  pull_request_target:
    paths:
      # Change docs dir to your repos docs dir
      - "docs/**.mdx"
      - "docs/**.docnav.json"
      - "docs/**.docapi.json"
      - "docs/**.devdocs.json"
      - "docs/**.jpg"
      - "docs/**.jpeg"
      - "docs/**.png"
      - "docs/**.gif"
    types: [closed, opened, synchronize]

jobs:
  publish:
    uses: elastic/workflows/.github/workflows/docs-elastic-co-publish.yml@main
    with:
      # Refers to Vercel project
      project-name: docs-elastic-co
      # Which prebuild step (dev or not)
      prebuild: wordlake
      # Docsmobile project dir
      repo: docs.elastic.co
    secrets:
      VERCEL_GITHUB_TOKEN: ${{ secrets.VERCEL_GITHUB_TOKEN }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID_DOCS_CO: ${{ secrets.VERCEL_PROJECT_ID_DOCS_CO }}
