name: search-ui docs prod deployer
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main for building
        uses: actions/checkout@v2

      - name: Checkout search-ui for building
        uses: actions/checkout@v2
        with:
          repository: elastic/search-ui
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/docsmobile

      - name: Show workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Deploy
        uses: elastic/builder@v21.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_SEARCH_UI }} #Required
          vercel-project-name: search-ui
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }} #Optional
          vercel-args: --prod
          github-comment: false
